export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CHANGE_PRODUCTS = 'CHANGE_PRODUCTS';
export const SUCCESS_FETCH_PRODUCTS = 'SUCCESS_FETCH_PRODUCTS';
export const FAILURE_FETCH_PRODUCTS = 'FAILURE_FETCH_PRODUCTS';